services:
  web:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    container_name: lamp-web
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
      - ./logs:/var/log/apache2
    environment:
      - DB_HOST=mariadb
      - DB_DATABASE=laravel_app
      - DB_USERNAME=laravel_user
      - DB_PASSWORD=laravel_password
      - DB_ROOT_PASSWORD=root_password_123
    depends_on:
      - mariadb
    networks:
      - lamp-network

  mariadb:
    image: mariadb:10.11
    container_name: lamp-mariadb
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root_password_123
      - MYSQL_DATABASE=laravel_app
      - MYSQL_USER=laravel_user
      - MYSQL_PASSWORD=laravel_password
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
    networks:
      - lamp-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.2
    container_name: lamp-phpmyadmin
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      - PMA_HOST=mariadb
      - PMA_PORT=3306
      - PMA_USER=root
      - PMA_PASSWORD=root_password_123
      - UPLOAD_LIMIT=256M
    depends_on:
      - mariadb
    networks:
      - lamp-network

volumes:
  mariadb_data:
    driver: local

networks:
  lamp-network:
    driver: bridge
